---
# EDITthe following:
# nano /root/OT-DockSucker/data/config.sh
# Fill in both restic and AWS details
# Execute this playbook with the following:
# cd ~/OT-DockSucker
# ansible-playbook -u root -k -i /etc/ansible/hostsCONVERT ansible/convert-to-docksucker.yml

- name: Convert existing nodes to DockSucker
  hosts: all
  gather_facts: yes

  tasks:
  - name: Set hostname
    hostname:
      name: falcor10

  - name: Make /root directory
    file:
      path: /root
      state: directory
      mode: '0770'

  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes

  - name: Clone OT-DockSucker git repository
    git:
      repo: 'https://github.com/calr0x/OT-DockSucker.git'
      dest: /root/OT-DockSucker
      force: yes
  
  - name: Copy node config file to server
    copy:
      src: ~/OT-DockSucker/data/config.sh
      dest: /root/OT-DockSucker/data/config.sh
      owner: root
      group: root
      mode: '0700'
  
  - name: Execute DockSucker installation
    shell: /root/OT-DockSucker/install-from-existing.sh >> OUTPUT
    args:
      chdir: /root/OT-DockSucker/