---
# EDITthe following:
# nano /root/OT-DockSucker/data/config.sh
# Fill in both restic and AWS details

- name: Convert existing nodes to DockSucker
  hosts: all
  gather_facts: yes

  tasks:
  - name: Set hostname
    hostname:
      name: falcor10

  - name: Make /root directory
    file:
      path: /root
      state: directory
      mode: '0770'

  - name: Install git
    apt:
      name: git
      state: present
      update_cache: yes

  - name: Clone OT-DockSucker git repository
    git:
      repo: 'https://github.com/calr0x/OT-DockSucker.git'
      dest: /root/OT-DockSucker
      force: yes
  
  - name: Copy node config file to server
    copy:
      src: ~/OT-DockSucker/data/config.sh
      dest: /root/OT-DockSucker/data/config.sh
      owner: root
      group: root
      mode: '0700'
  
  - name: Execute DockSucker installation
    shell: /root/OT-DockSucker/install-from-existing.sh >> OUTPUT
    args:
      chdir: /root/OT-DockSucker/

  - name: Edit node config with IP address
    replace:
      path: /root/Cosmic_OverlayV2/configurations/node_config.json
      regexp: IP_OF_YOUR_SERVER
      replace: "{{ ansible_facts['default_ipv4']['address'] }}"

  - name: Edit node config with initial deposit amount
    replace:
      path: /root/Cosmic_OverlayV2/configurations/node_config.json
      regexp: INITIAL_DEPOSIT_AMOUNT_HERE
      replace: "{{ initial_deposit_amount }}"

  - name: Edit node config with operational wallet public key
    replace:
      path: /root/Cosmic_OverlayV2/configurations/node_config.json
      regexp: PUBLIC_KEY_OF_YOUR_WALLET
      replace: "{{ op_pub_key }}"

  - name: Edit node config with operational wallet private key
    replace:
      path: /root/Cosmic_OverlayV2/configurations/node_config.json
      regexp: PRIVATE_KEY_OF_YOUR_WALLET
      replace: "{{ op_priv_key }}"

  - name: Edit node config with management wallet public key
    replace:
      path: /root/Cosmic_OverlayV2/configurations/node_config.json
      regexp: PUBLIC_KEY_OF_MANAGEMENT_WALLET
      replace: "{{ mgmt_pub_key }}"

  - name: Edit node config with dh_price_factor
    replace:
      path: /root/Cosmic_OverlayV2/configurations/node_config.json
      regexp: DH_PRICE_FACTOR
      replace: "{{ dh_price_factor }}"

  - name: Edit node config with dh_max_holding_time_in_minutes
    replace:
      path: /root/Cosmic_OverlayV2/configurations/node_config.json
      regexp: DH_HOLDING_TIME_MINUTES
      replace: "{{ dh_max_holding_time_in_minutes }}"